Neural Net Impl
Awesome-sw8-project/experiments pull request #12
Opened 2021-04-17 12:54 UTC by abiram98

Might be a good idea to also support testing of two models; one for X and Y, and another for just floors.

2021-04-17 13:50 UTC, elaurs commented
ABI DET ER LØRDAG

2021-04-17 13:53 UTC, elaurs approved these changes, later dismissed

2021-04-17 13:54 UTC, elaurs commented
men det er okay når det ser så godt ud <3 er der også en model 1?

2021-04-18 18:53 UTC, abiram98 commented
> men det er okay når det ser så godt ud <3 er der også en model 1?

Ja, det ligger vidst på Kaggle som min private notebook. Men den er nok ikke relevant at have med, siden den performer dårligt.

2021-04-18 19:08 UTC, MrPekar98 requested changes

2021-04-18 19:08 UTC, MrPekar98 commented on .gitignore
> +results
Den her linje kommer til at fjerne linje 3. Så vil mine Python commits blive ændret.

Måske skriv `!results/*/*.py` i stedet for PDR og skriv `results/*` i stedet for linje 2.

2021-04-18 19:11 UTC, MrPekar98 reviewed
Har du kørt det igennem evaluatoren?

2021-04-18 19:17 UTC, abiram98 commented
> Har du kørt det igennem evaluatoren?

Nej, det er allerede en udfordring at holde træningen på under 9 timer uden evaluatoren, hvilket er nødvendigt for at kunne køre det på Kaggle. Det giver desuden ikke rigtig mening at køre det igennem evaluatoren for ML algoritmerne. For modeller, som trænes i iterationer/epochs, giver det bedre mening at evaluere på performance ift. iterationerne, og det data har vi.

2021-04-18 19:20 UTC, MrPekar98 commented
Fair. Men hvorfor træne i iterationer? Hvad giver det?

2021-04-19 07:28 UTC, MrPekar98 approved these changes

2021-04-23 10:48 UTC, elaurs approved these changes
men kun fordi martin er træls :)

2021-04-23 10:48 UTC, MikkelFilip approved these changes
Enig

2021-04-23 11:07 UTC, melanieselman approved these changes

2021-04-23 11:07 UTC, ceciliehyrup1 approved these changes

2021-04-23 11:14 UTC, merged